CREATE TABLE EXAMPLE (UUID varchar(255) PRIMARY KEY, PARAM varchar(1024))
CREATE TABLE EXAMPLE_USERS (USERNAME varchar(255) PRIMARY KEY, PASSWORD varchar(255))
CREATE TABLE EXAMPLE_SESSIONS (ID varchar(255) PRIMARY KEY)