// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/META-INF/server.proto

package org.deephacks.westty.tests;

public final class ServerMessages {
  private ServerMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JsonMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 protoType = 300;
    boolean hasProtoType();
    int getProtoType();
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string json = 2;
    boolean hasJson();
    String getJson();
  }
  public static final class JsonMessage extends
      com.google.protobuf.GeneratedMessage
      implements JsonMessageOrBuilder {
    // Use JsonMessage.newBuilder() to construct.
    private JsonMessage(Builder builder) {
      super(builder);
    }
    private JsonMessage(boolean noInit) {}
    
    private static final JsonMessage defaultInstance;
    public static JsonMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public JsonMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_JsonMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_JsonMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 protoType = 300;
    public static final int PROTOTYPE_FIELD_NUMBER = 300;
    private int protoType_;
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProtoType() {
      return protoType_;
    }
    
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string json = 2;
    public static final int JSON_FIELD_NUMBER = 2;
    private java.lang.Object json_;
    public boolean hasJson() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getJson() {
      java.lang.Object ref = json_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          json_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getJsonBytes() {
      java.lang.Object ref = json_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        json_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      protoType_ = 0;
      id_ = "";
      json_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(2, getJsonBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(300, protoType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getJsonBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(300, protoType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.JsonMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deephacks.westty.tests.ServerMessages.JsonMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_JsonMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_JsonMessage_fieldAccessorTable;
      }
      
      // Construct using org.deephacks.westty.tests.ServerMessages.JsonMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        json_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deephacks.westty.tests.ServerMessages.JsonMessage.getDescriptor();
      }
      
      public org.deephacks.westty.tests.ServerMessages.JsonMessage getDefaultInstanceForType() {
        return org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance();
      }
      
      public org.deephacks.westty.tests.ServerMessages.JsonMessage build() {
        org.deephacks.westty.tests.ServerMessages.JsonMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.deephacks.westty.tests.ServerMessages.JsonMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.deephacks.westty.tests.ServerMessages.JsonMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.deephacks.westty.tests.ServerMessages.JsonMessage buildPartial() {
        org.deephacks.westty.tests.ServerMessages.JsonMessage result = new org.deephacks.westty.tests.ServerMessages.JsonMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.json_ = json_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deephacks.westty.tests.ServerMessages.JsonMessage) {
          return mergeFrom((org.deephacks.westty.tests.ServerMessages.JsonMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.deephacks.westty.tests.ServerMessages.JsonMessage other) {
        if (other == org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasJson()) {
          setJson(other.getJson());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasJson()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000002;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000004;
              json_ = input.readBytes();
              break;
            }
            case 2400: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 protoType = 300;
      private int protoType_ ;
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProtoType() {
        return protoType_;
      }
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
      }
      
      // required string json = 2;
      private java.lang.Object json_ = "";
      public boolean hasJson() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getJson() {
        java.lang.Object ref = json_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          json_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setJson(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        json_ = value;
        onChanged();
        return this;
      }
      public Builder clearJson() {
        bitField0_ = (bitField0_ & ~0x00000004);
        json_ = getDefaultInstance().getJson();
        onChanged();
        return this;
      }
      void setJson(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        json_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:westty.tests.JsonMessage)
    }
    
    static {
      defaultInstance = new JsonMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:westty.tests.JsonMessage)
  }
  
  public interface CreateRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 protoType = 301;
    boolean hasProtoType();
    int getProtoType();
    
    // required .westty.tests.JsonMessage json = 1;
    boolean hasJson();
    org.deephacks.westty.tests.ServerMessages.JsonMessage getJson();
    org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder getJsonOrBuilder();
  }
  public static final class CreateRequest extends
      com.google.protobuf.GeneratedMessage
      implements CreateRequestOrBuilder {
    // Use CreateRequest.newBuilder() to construct.
    private CreateRequest(Builder builder) {
      super(builder);
    }
    private CreateRequest(boolean noInit) {}
    
    private static final CreateRequest defaultInstance;
    public static CreateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_CreateRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_CreateRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 protoType = 301;
    public static final int PROTOTYPE_FIELD_NUMBER = 301;
    private int protoType_;
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProtoType() {
      return protoType_;
    }
    
    // required .westty.tests.JsonMessage json = 1;
    public static final int JSON_FIELD_NUMBER = 1;
    private org.deephacks.westty.tests.ServerMessages.JsonMessage json_;
    public boolean hasJson() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.deephacks.westty.tests.ServerMessages.JsonMessage getJson() {
      return json_;
    }
    public org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder getJsonOrBuilder() {
      return json_;
    }
    
    private void initFields() {
      protoType_ = 0;
      json_ = org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasJson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getJson().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(1, json_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(301, protoType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, json_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(301, protoType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.CreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deephacks.westty.tests.ServerMessages.CreateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deephacks.westty.tests.ServerMessages.CreateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_CreateRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_CreateRequest_fieldAccessorTable;
      }
      
      // Construct using org.deephacks.westty.tests.ServerMessages.CreateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJsonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (jsonBuilder_ == null) {
          json_ = org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance();
        } else {
          jsonBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deephacks.westty.tests.ServerMessages.CreateRequest.getDescriptor();
      }
      
      public org.deephacks.westty.tests.ServerMessages.CreateRequest getDefaultInstanceForType() {
        return org.deephacks.westty.tests.ServerMessages.CreateRequest.getDefaultInstance();
      }
      
      public org.deephacks.westty.tests.ServerMessages.CreateRequest build() {
        org.deephacks.westty.tests.ServerMessages.CreateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.deephacks.westty.tests.ServerMessages.CreateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.deephacks.westty.tests.ServerMessages.CreateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.deephacks.westty.tests.ServerMessages.CreateRequest buildPartial() {
        org.deephacks.westty.tests.ServerMessages.CreateRequest result = new org.deephacks.westty.tests.ServerMessages.CreateRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (jsonBuilder_ == null) {
          result.json_ = json_;
        } else {
          result.json_ = jsonBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deephacks.westty.tests.ServerMessages.CreateRequest) {
          return mergeFrom((org.deephacks.westty.tests.ServerMessages.CreateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.deephacks.westty.tests.ServerMessages.CreateRequest other) {
        if (other == org.deephacks.westty.tests.ServerMessages.CreateRequest.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (other.hasJson()) {
          mergeJson(other.getJson());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasJson()) {
          
          return false;
        }
        if (!getJson().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder subBuilder = org.deephacks.westty.tests.ServerMessages.JsonMessage.newBuilder();
              if (hasJson()) {
                subBuilder.mergeFrom(getJson());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setJson(subBuilder.buildPartial());
              break;
            }
            case 2408: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 protoType = 301;
      private int protoType_ ;
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProtoType() {
        return protoType_;
      }
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }
      
      // required .westty.tests.JsonMessage json = 1;
      private org.deephacks.westty.tests.ServerMessages.JsonMessage json_ = org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.deephacks.westty.tests.ServerMessages.JsonMessage, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder, org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> jsonBuilder_;
      public boolean hasJson() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessage getJson() {
        if (jsonBuilder_ == null) {
          return json_;
        } else {
          return jsonBuilder_.getMessage();
        }
      }
      public Builder setJson(org.deephacks.westty.tests.ServerMessages.JsonMessage value) {
        if (jsonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          json_ = value;
          onChanged();
        } else {
          jsonBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setJson(
          org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder builderForValue) {
        if (jsonBuilder_ == null) {
          json_ = builderForValue.build();
          onChanged();
        } else {
          jsonBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeJson(org.deephacks.westty.tests.ServerMessages.JsonMessage value) {
        if (jsonBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              json_ != org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance()) {
            json_ =
              org.deephacks.westty.tests.ServerMessages.JsonMessage.newBuilder(json_).mergeFrom(value).buildPartial();
          } else {
            json_ = value;
          }
          onChanged();
        } else {
          jsonBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearJson() {
        if (jsonBuilder_ == null) {
          json_ = org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance();
          onChanged();
        } else {
          jsonBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder getJsonBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getJsonFieldBuilder().getBuilder();
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder getJsonOrBuilder() {
        if (jsonBuilder_ != null) {
          return jsonBuilder_.getMessageOrBuilder();
        } else {
          return json_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.deephacks.westty.tests.ServerMessages.JsonMessage, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder, org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> 
          getJsonFieldBuilder() {
        if (jsonBuilder_ == null) {
          jsonBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.deephacks.westty.tests.ServerMessages.JsonMessage, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder, org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder>(
                  json_,
                  getParentForChildren(),
                  isClean());
          json_ = null;
        }
        return jsonBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:westty.tests.CreateRequest)
    }
    
    static {
      defaultInstance = new CreateRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:westty.tests.CreateRequest)
  }
  
  public interface ListRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 protoType = 302;
    boolean hasProtoType();
    int getProtoType();
  }
  public static final class ListRequest extends
      com.google.protobuf.GeneratedMessage
      implements ListRequestOrBuilder {
    // Use ListRequest.newBuilder() to construct.
    private ListRequest(Builder builder) {
      super(builder);
    }
    private ListRequest(boolean noInit) {}
    
    private static final ListRequest defaultInstance;
    public static ListRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ListRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 protoType = 302;
    public static final int PROTOTYPE_FIELD_NUMBER = 302;
    private int protoType_;
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProtoType() {
      return protoType_;
    }
    
    private void initFields() {
      protoType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(302, protoType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(302, protoType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deephacks.westty.tests.ServerMessages.ListRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deephacks.westty.tests.ServerMessages.ListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListRequest_fieldAccessorTable;
      }
      
      // Construct using org.deephacks.westty.tests.ServerMessages.ListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deephacks.westty.tests.ServerMessages.ListRequest.getDescriptor();
      }
      
      public org.deephacks.westty.tests.ServerMessages.ListRequest getDefaultInstanceForType() {
        return org.deephacks.westty.tests.ServerMessages.ListRequest.getDefaultInstance();
      }
      
      public org.deephacks.westty.tests.ServerMessages.ListRequest build() {
        org.deephacks.westty.tests.ServerMessages.ListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.deephacks.westty.tests.ServerMessages.ListRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.deephacks.westty.tests.ServerMessages.ListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.deephacks.westty.tests.ServerMessages.ListRequest buildPartial() {
        org.deephacks.westty.tests.ServerMessages.ListRequest result = new org.deephacks.westty.tests.ServerMessages.ListRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deephacks.westty.tests.ServerMessages.ListRequest) {
          return mergeFrom((org.deephacks.westty.tests.ServerMessages.ListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.deephacks.westty.tests.ServerMessages.ListRequest other) {
        if (other == org.deephacks.westty.tests.ServerMessages.ListRequest.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 2416: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 protoType = 302;
      private int protoType_ ;
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProtoType() {
        return protoType_;
      }
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:westty.tests.ListRequest)
    }
    
    static {
      defaultInstance = new ListRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:westty.tests.ListRequest)
  }
  
  public interface ListResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 protoType = 303;
    boolean hasProtoType();
    int getProtoType();
    
    // repeated .westty.tests.JsonMessage json = 1;
    java.util.List<org.deephacks.westty.tests.ServerMessages.JsonMessage> 
        getJsonList();
    org.deephacks.westty.tests.ServerMessages.JsonMessage getJson(int index);
    int getJsonCount();
    java.util.List<? extends org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> 
        getJsonOrBuilderList();
    org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder getJsonOrBuilder(
        int index);
  }
  public static final class ListResponse extends
      com.google.protobuf.GeneratedMessage
      implements ListResponseOrBuilder {
    // Use ListResponse.newBuilder() to construct.
    private ListResponse(Builder builder) {
      super(builder);
    }
    private ListResponse(boolean noInit) {}
    
    private static final ListResponse defaultInstance;
    public static ListResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 protoType = 303;
    public static final int PROTOTYPE_FIELD_NUMBER = 303;
    private int protoType_;
    public boolean hasProtoType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getProtoType() {
      return protoType_;
    }
    
    // repeated .westty.tests.JsonMessage json = 1;
    public static final int JSON_FIELD_NUMBER = 1;
    private java.util.List<org.deephacks.westty.tests.ServerMessages.JsonMessage> json_;
    public java.util.List<org.deephacks.westty.tests.ServerMessages.JsonMessage> getJsonList() {
      return json_;
    }
    public java.util.List<? extends org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> 
        getJsonOrBuilderList() {
      return json_;
    }
    public int getJsonCount() {
      return json_.size();
    }
    public org.deephacks.westty.tests.ServerMessages.JsonMessage getJson(int index) {
      return json_.get(index);
    }
    public org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder getJsonOrBuilder(
        int index) {
      return json_.get(index);
    }
    
    private void initFields() {
      protoType_ = 0;
      json_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getJsonCount(); i++) {
        if (!getJson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < json_.size(); i++) {
        output.writeMessage(1, json_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(303, protoType_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < json_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, json_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(303, protoType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.deephacks.westty.tests.ServerMessages.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.deephacks.westty.tests.ServerMessages.ListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.deephacks.westty.tests.ServerMessages.ListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deephacks.westty.tests.ServerMessages.internal_static_westty_tests_ListResponse_fieldAccessorTable;
      }
      
      // Construct using org.deephacks.westty.tests.ServerMessages.ListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJsonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        protoType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (jsonBuilder_ == null) {
          json_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          jsonBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deephacks.westty.tests.ServerMessages.ListResponse.getDescriptor();
      }
      
      public org.deephacks.westty.tests.ServerMessages.ListResponse getDefaultInstanceForType() {
        return org.deephacks.westty.tests.ServerMessages.ListResponse.getDefaultInstance();
      }
      
      public org.deephacks.westty.tests.ServerMessages.ListResponse build() {
        org.deephacks.westty.tests.ServerMessages.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.deephacks.westty.tests.ServerMessages.ListResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.deephacks.westty.tests.ServerMessages.ListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.deephacks.westty.tests.ServerMessages.ListResponse buildPartial() {
        org.deephacks.westty.tests.ServerMessages.ListResponse result = new org.deephacks.westty.tests.ServerMessages.ListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.protoType_ = protoType_;
        if (jsonBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            json_ = java.util.Collections.unmodifiableList(json_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.json_ = json_;
        } else {
          result.json_ = jsonBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deephacks.westty.tests.ServerMessages.ListResponse) {
          return mergeFrom((org.deephacks.westty.tests.ServerMessages.ListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.deephacks.westty.tests.ServerMessages.ListResponse other) {
        if (other == org.deephacks.westty.tests.ServerMessages.ListResponse.getDefaultInstance()) return this;
        if (other.hasProtoType()) {
          setProtoType(other.getProtoType());
        }
        if (jsonBuilder_ == null) {
          if (!other.json_.isEmpty()) {
            if (json_.isEmpty()) {
              json_ = other.json_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureJsonIsMutable();
              json_.addAll(other.json_);
            }
            onChanged();
          }
        } else {
          if (!other.json_.isEmpty()) {
            if (jsonBuilder_.isEmpty()) {
              jsonBuilder_.dispose();
              jsonBuilder_ = null;
              json_ = other.json_;
              bitField0_ = (bitField0_ & ~0x00000002);
              jsonBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getJsonFieldBuilder() : null;
            } else {
              jsonBuilder_.addAllMessages(other.json_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getJsonCount(); i++) {
          if (!getJson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder subBuilder = org.deephacks.westty.tests.ServerMessages.JsonMessage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addJson(subBuilder.buildPartial());
              break;
            }
            case 2424: {
              bitField0_ |= 0x00000001;
              protoType_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 protoType = 303;
      private int protoType_ ;
      public boolean hasProtoType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getProtoType() {
        return protoType_;
      }
      public Builder setProtoType(int value) {
        bitField0_ |= 0x00000001;
        protoType_ = value;
        onChanged();
        return this;
      }
      public Builder clearProtoType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        protoType_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .westty.tests.JsonMessage json = 1;
      private java.util.List<org.deephacks.westty.tests.ServerMessages.JsonMessage> json_ =
        java.util.Collections.emptyList();
      private void ensureJsonIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          json_ = new java.util.ArrayList<org.deephacks.westty.tests.ServerMessages.JsonMessage>(json_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.deephacks.westty.tests.ServerMessages.JsonMessage, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder, org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> jsonBuilder_;
      
      public java.util.List<org.deephacks.westty.tests.ServerMessages.JsonMessage> getJsonList() {
        if (jsonBuilder_ == null) {
          return java.util.Collections.unmodifiableList(json_);
        } else {
          return jsonBuilder_.getMessageList();
        }
      }
      public int getJsonCount() {
        if (jsonBuilder_ == null) {
          return json_.size();
        } else {
          return jsonBuilder_.getCount();
        }
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessage getJson(int index) {
        if (jsonBuilder_ == null) {
          return json_.get(index);
        } else {
          return jsonBuilder_.getMessage(index);
        }
      }
      public Builder setJson(
          int index, org.deephacks.westty.tests.ServerMessages.JsonMessage value) {
        if (jsonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJsonIsMutable();
          json_.set(index, value);
          onChanged();
        } else {
          jsonBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setJson(
          int index, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder builderForValue) {
        if (jsonBuilder_ == null) {
          ensureJsonIsMutable();
          json_.set(index, builderForValue.build());
          onChanged();
        } else {
          jsonBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addJson(org.deephacks.westty.tests.ServerMessages.JsonMessage value) {
        if (jsonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJsonIsMutable();
          json_.add(value);
          onChanged();
        } else {
          jsonBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addJson(
          int index, org.deephacks.westty.tests.ServerMessages.JsonMessage value) {
        if (jsonBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJsonIsMutable();
          json_.add(index, value);
          onChanged();
        } else {
          jsonBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addJson(
          org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder builderForValue) {
        if (jsonBuilder_ == null) {
          ensureJsonIsMutable();
          json_.add(builderForValue.build());
          onChanged();
        } else {
          jsonBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addJson(
          int index, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder builderForValue) {
        if (jsonBuilder_ == null) {
          ensureJsonIsMutable();
          json_.add(index, builderForValue.build());
          onChanged();
        } else {
          jsonBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllJson(
          java.lang.Iterable<? extends org.deephacks.westty.tests.ServerMessages.JsonMessage> values) {
        if (jsonBuilder_ == null) {
          ensureJsonIsMutable();
          super.addAll(values, json_);
          onChanged();
        } else {
          jsonBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearJson() {
        if (jsonBuilder_ == null) {
          json_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          jsonBuilder_.clear();
        }
        return this;
      }
      public Builder removeJson(int index) {
        if (jsonBuilder_ == null) {
          ensureJsonIsMutable();
          json_.remove(index);
          onChanged();
        } else {
          jsonBuilder_.remove(index);
        }
        return this;
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder getJsonBuilder(
          int index) {
        return getJsonFieldBuilder().getBuilder(index);
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder getJsonOrBuilder(
          int index) {
        if (jsonBuilder_ == null) {
          return json_.get(index);  } else {
          return jsonBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> 
           getJsonOrBuilderList() {
        if (jsonBuilder_ != null) {
          return jsonBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(json_);
        }
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder addJsonBuilder() {
        return getJsonFieldBuilder().addBuilder(
            org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance());
      }
      public org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder addJsonBuilder(
          int index) {
        return getJsonFieldBuilder().addBuilder(
            index, org.deephacks.westty.tests.ServerMessages.JsonMessage.getDefaultInstance());
      }
      public java.util.List<org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder> 
           getJsonBuilderList() {
        return getJsonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.deephacks.westty.tests.ServerMessages.JsonMessage, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder, org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder> 
          getJsonFieldBuilder() {
        if (jsonBuilder_ == null) {
          jsonBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.deephacks.westty.tests.ServerMessages.JsonMessage, org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder, org.deephacks.westty.tests.ServerMessages.JsonMessageOrBuilder>(
                  json_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          json_ = null;
        }
        return jsonBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:westty.tests.ListResponse)
    }
    
    static {
      defaultInstance = new ListResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:westty.tests.ListResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_westty_tests_JsonMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_westty_tests_JsonMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_westty_tests_CreateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_westty_tests_CreateRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_westty_tests_ListRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_westty_tests_ListRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_westty_tests_ListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_westty_tests_ListResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/resources/META-INF/server.pro" +
      "to\022\014westty.tests\";\n\013JsonMessage\022\022\n\tproto" +
      "Type\030\254\002 \001(\r\022\n\n\002id\030\001 \002(\t\022\014\n\004json\030\002 \002(\t\"L\n" +
      "\rCreateRequest\022\022\n\tprotoType\030\255\002 \001(\r\022\'\n\004js" +
      "on\030\001 \002(\0132\031.westty.tests.JsonMessage\"!\n\013L" +
      "istRequest\022\022\n\tprotoType\030\256\002 \001(\r\"K\n\014ListRe" +
      "sponse\022\022\n\tprotoType\030\257\002 \001(\r\022\'\n\004json\030\001 \003(\013" +
      "2\031.westty.tests.JsonMessageB,\n\032org.deeph" +
      "acks.westty.testsB\016ServerMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_westty_tests_JsonMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_westty_tests_JsonMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_westty_tests_JsonMessage_descriptor,
              new java.lang.String[] { "ProtoType", "Id", "Json", },
              org.deephacks.westty.tests.ServerMessages.JsonMessage.class,
              org.deephacks.westty.tests.ServerMessages.JsonMessage.Builder.class);
          internal_static_westty_tests_CreateRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_westty_tests_CreateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_westty_tests_CreateRequest_descriptor,
              new java.lang.String[] { "ProtoType", "Json", },
              org.deephacks.westty.tests.ServerMessages.CreateRequest.class,
              org.deephacks.westty.tests.ServerMessages.CreateRequest.Builder.class);
          internal_static_westty_tests_ListRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_westty_tests_ListRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_westty_tests_ListRequest_descriptor,
              new java.lang.String[] { "ProtoType", },
              org.deephacks.westty.tests.ServerMessages.ListRequest.class,
              org.deephacks.westty.tests.ServerMessages.ListRequest.Builder.class);
          internal_static_westty_tests_ListResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_westty_tests_ListResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_westty_tests_ListResponse_descriptor,
              new java.lang.String[] { "ProtoType", "Json", },
              org.deephacks.westty.tests.ServerMessages.ListResponse.class,
              org.deephacks.westty.tests.ServerMessages.ListResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
